{"name": "test_case_catch_exception", "status": "passed", "attachments": [{"name": "log", "source": "35a4ba43-9137-49aa-b07f-fe6cb5f2d5b3-attachment.txt", "type": "text/plain"}], "start": 1627199625077, "stop": 1627199625078, "uuid": "bfb1e393-ae19-4098-a39e-511c60d61bd9", "historyId": "64ea4197fec1cd774423a7299347767b", "testCaseId": "af4145185e89745309824c8cd558d1df", "fullName": "test_exception#test_case_catch_exception", "labels": [{"name": "suite", "value": "test_exception"}, {"name": "host", "value": "ccyangdeMacBook-Pro.local"}, {"name": "thread", "value": "58448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_exception"}]}