{"name": "test_case_catch_exception", "status": "passed", "attachments": [{"name": "log", "source": "153dfe82-ca69-44f9-8efb-e6d7e590db8a-attachment.txt", "type": "text/plain"}], "start": 1627199677984, "stop": 1627199677985, "uuid": "bf46f327-602c-4c15-add9-cd9b1c9bb87a", "historyId": "64ea4197fec1cd774423a7299347767b", "testCaseId": "af4145185e89745309824c8cd558d1df", "fullName": "test_exception#test_case_catch_exception", "labels": [{"name": "suite", "value": "test_exception"}, {"name": "host", "value": "ccyangdeMacBook-Pro.local"}, {"name": "thread", "value": "58486-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_exception"}]}