2021-07-19 00:40:26 [DEBUG] Looking for locale `en_US` in provider `faker.providers.address`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.address` has been localized to `en_US`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Looking for locale `en_US` in provider `faker.providers.automotive`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.automotive` has been localized to `en_US`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Looking for locale `en_US` in provider `faker.providers.bank`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider. (factory.py:101)
2021-07-19 00:40:26 [DEBUG] Looking for locale `en_US` in provider `faker.providers.barcode`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.barcode` has been localized to `en_US`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Looking for locale `en_US` in provider `faker.providers.color`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.color` has been localized to `en_US`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Looking for locale `en_US` in provider `faker.providers.company`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.company` has been localized to `en_US`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Looking for locale `en_US` in provider `faker.providers.credit_card`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.credit_card` has been localized to `en_US`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Looking for locale `en_US` in provider `faker.providers.currency`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.currency` has been localized to `en_US`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Looking for locale `en_US` in provider `faker.providers.date_time`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.date_time` has been localized to `en_US`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider. (factory.py:113)
2021-07-19 00:40:26 [DEBUG] Looking for locale `en_US` in provider `faker.providers.geo`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.geo` has been localized to `en_US`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Looking for locale `en_US` in provider `faker.providers.internet`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.internet` has been localized to `en_US`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider. (factory.py:113)
2021-07-19 00:40:26 [DEBUG] Looking for locale `en_US` in provider `faker.providers.job`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.job` has been localized to `en_US`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Looking for locale `en_US` in provider `faker.providers.lorem`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.lorem` has been localized to `en_US`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Looking for locale `en_US` in provider `faker.providers.misc`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.misc` has been localized to `en_US`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Looking for locale `en_US` in provider `faker.providers.person`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.person` has been localized to `en_US`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Looking for locale `en_US` in provider `faker.providers.phone_number`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.phone_number` has been localized to `en_US`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider. (factory.py:113)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider. (factory.py:113)
2021-07-19 00:40:26 [DEBUG] Looking for locale `en_US` in provider `faker.providers.ssn`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.ssn` has been localized to `en_US`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider. (factory.py:113)
2021-07-19 00:40:26 [DEBUG] Starting new HTTPS connection (1): qyapi.weixin.qq.com:443 (connectionpool.py:971)
2021-07-19 00:40:26 [DEBUG] https://qyapi.weixin.qq.com:443 "GET /cgi-bin/gettoken?corpid=wwb233c1264ce7e17c&corpsecret=OZYrQR6IT2cAna-MfIoClMm9f4ehhNw_cX5_D-ZyTJE HTTP/1.1" 200 277 (connectionpool.py:452)
2021-07-19 00:40:26 [INFO] got token 5Ny9MzxbrGVFqUiDStaOp3YGRS3F_uHqxa8ZvoK0Riq-S1KsDynpfOBBQA2TxDztSeA2sHfCmr9zfeTTZefNis9IPSpQ07cDc74iu1bq0yd1aeLsGTWgd_n146sGroFLIBKMVuYLA5cckgx0UVJxenjBsrTt2Nlz7t0XRPWgGal_N_cnDZrNTuTkYU1MvbfKF7xoGq4Sq7dKomLIJPOT3Q (base_api.py:18)
2021-07-19 00:40:26 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.address`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.address` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.automotive`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.automotive`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:26 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.bank`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider. (factory.py:101)
2021-07-19 00:40:26 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.barcode`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.barcode`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:26 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.color`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.color`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:26 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.company`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.company` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.credit_card`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.credit_card`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:26 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.currency`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.currency`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:26 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.date_time`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.date_time`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.file` does not feature localization. Specified locale `zh_CN` is not utilized for this provider. (factory.py:113)
2021-07-19 00:40:26 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.geo`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.geo`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:26 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.internet`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.internet` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.isbn` does not feature localization. Specified locale `zh_CN` is not utilized for this provider. (factory.py:113)
2021-07-19 00:40:26 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.job`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.job` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.lorem`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.lorem` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.misc`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.misc`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:26 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.person`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.person` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.phone_number`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.phone_number` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.profile` does not feature localization. Specified locale `zh_CN` is not utilized for this provider. (factory.py:113)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.python` does not feature localization. Specified locale `zh_CN` is not utilized for this provider. (factory.py:113)
2021-07-19 00:40:26 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.ssn`. (factory.py:94)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.ssn` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:26 [DEBUG] Provider `faker.providers.user_agent` does not feature localization. Specified locale `zh_CN` is not utilized for this provider. (factory.py:113)
2021-07-19 00:40:26 [INFO] sending method:POST to url:https://qyapi.weixin.qq.com/cgi-bin/user/create?access_token=5Ny9MzxbrGVFqUiDStaOp3YGRS3F_uHqxa8ZvoK0Riq-S1KsDynpfOBBQA2TxDztSeA2sHfCmr9zfeTTZefNis9IPSpQ07cDc74iu1bq0yd1aeLsGTWgd_n146sGroFLIBKMVuYLA5cckgx0UVJxenjBsrTt2Nlz7t0XRPWgGal_N_cnDZrNTuTkYU1MvbfKF7xoGq4Sq7dKomLIJPOT3Q (base_api.py:23)
2021-07-19 00:40:26 [DEBUG] Starting new HTTPS connection (1): qyapi.weixin.qq.com:443 (connectionpool.py:971)
2021-07-19 00:40:27 [DEBUG] https://qyapi.weixin.qq.com:443 "POST /cgi-bin/user/create?access_token=5Ny9MzxbrGVFqUiDStaOp3YGRS3F_uHqxa8ZvoK0Riq-S1KsDynpfOBBQA2TxDztSeA2sHfCmr9zfeTTZefNis9IPSpQ07cDc74iu1bq0yd1aeLsGTWgd_n146sGroFLIBKMVuYLA5cckgx0UVJxenjBsrTt2Nlz7t0XRPWgGal_N_cnDZrNTuTkYU1MvbfKF7xoGq4Sq7dKomLIJPOT3Q HTTP/1.1" 200 32 (connectionpool.py:452)
2021-07-19 00:40:27 [DEBUG] add user result: {'errcode': 0, 'errmsg': 'created'} (user.py:19)
2021-07-19 00:40:27 [INFO] sending method:GET to url:https://qyapi.weixin.qq.com/cgi-bin/user/get?access_token=5Ny9MzxbrGVFqUiDStaOp3YGRS3F_uHqxa8ZvoK0Riq-S1KsDynpfOBBQA2TxDztSeA2sHfCmr9zfeTTZefNis9IPSpQ07cDc74iu1bq0yd1aeLsGTWgd_n146sGroFLIBKMVuYLA5cckgx0UVJxenjBsrTt2Nlz7t0XRPWgGal_N_cnDZrNTuTkYU1MvbfKF7xoGq4Sq7dKomLIJPOT3Q&userid=YangChuChao (base_api.py:23)
2021-07-19 00:40:27 [DEBUG] Starting new HTTPS connection (1): qyapi.weixin.qq.com:443 (connectionpool.py:971)
2021-07-19 00:40:27 [DEBUG] https://qyapi.weixin.qq.com:443 "GET /cgi-bin/user/get?access_token=5Ny9MzxbrGVFqUiDStaOp3YGRS3F_uHqxa8ZvoK0Riq-S1KsDynpfOBBQA2TxDztSeA2sHfCmr9zfeTTZefNis9IPSpQ07cDc74iu1bq0yd1aeLsGTWgd_n146sGroFLIBKMVuYLA5cckgx0UVJxenjBsrTt2Nlz7t0XRPWgGal_N_cnDZrNTuTkYU1MvbfKF7xoGq4Sq7dKomLIJPOT3Q&userid=YangChuChao HTTP/1.1" 200 606 (connectionpool.py:452)
2021-07-19 00:40:27 [DEBUG] get user result: {'errcode': 0, 'errmsg': 'ok', 'userid': 'YangChuChao', 'name': '杨楚超', 'department': [1], 'position': '', 'mobile': '13524296350', 'gender': '1', 'email': '', 'avatar': 'http://wework.qpic.cn/bizmail/exjDKawdQico60WvJ3ibH6tpDQQvKqcsicZiaGWNicibTYHLAoY2YkdRjUaw/0', 'status': 1, 'isleader': 0, 'extattr': {'attrs': []}, 'telephone': '', 'enable': 1, 'hide_mobile': 0, 'order': [0], 'main_department': 1, 'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc6924c10efa44fec8', 'alias': '', 'is_leader_in_dept': [0], 'thumb_avatar': 'http://wework.qpic.cn/bizmail/exjDKawdQico60WvJ3ibH6tpDQQvKqcsicZiaGWNicibTYHLAoY2YkdRjUaw/100'} (user.py:24)
2021-07-19 00:40:27 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.address`. (factory.py:94)
2021-07-19 00:40:27 [DEBUG] Provider `faker.providers.address` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:27 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.automotive`. (factory.py:94)
2021-07-19 00:40:27 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.automotive`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:27 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.bank`. (factory.py:94)
2021-07-19 00:40:27 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider. (factory.py:101)
2021-07-19 00:40:27 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.barcode`. (factory.py:94)
2021-07-19 00:40:27 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.barcode`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:27 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.color`. (factory.py:94)
2021-07-19 00:40:27 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.color`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:27 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.company`. (factory.py:94)
2021-07-19 00:40:27 [DEBUG] Provider `faker.providers.company` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:27 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.credit_card`. (factory.py:94)
2021-07-19 00:40:27 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.credit_card`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:27 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.currency`. (factory.py:94)
2021-07-19 00:40:27 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.currency`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:27 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.date_time`. (factory.py:94)
2021-07-19 00:40:27 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.date_time`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:27 [DEBUG] Provider `faker.providers.file` does not feature localization. Specified locale `zh_CN` is not utilized for this provider. (factory.py:113)
2021-07-19 00:40:27 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.geo`. (factory.py:94)
2021-07-19 00:40:27 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.geo`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:27 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.internet`. (factory.py:94)
2021-07-19 00:40:27 [DEBUG] Provider `faker.providers.internet` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:27 [DEBUG] Provider `faker.providers.isbn` does not feature localization. Specified locale `zh_CN` is not utilized for this provider. (factory.py:113)
2021-07-19 00:40:27 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.job`. (factory.py:94)
2021-07-19 00:40:27 [DEBUG] Provider `faker.providers.job` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:27 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.lorem`. (factory.py:94)
2021-07-19 00:40:27 [DEBUG] Provider `faker.providers.lorem` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:27 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.misc`. (factory.py:94)
2021-07-19 00:40:27 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.misc`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:27 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.person`. (factory.py:94)
2021-07-19 00:40:27 [DEBUG] Provider `faker.providers.person` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:27 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.phone_number`. (factory.py:94)
2021-07-19 00:40:27 [DEBUG] Provider `faker.providers.phone_number` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:27 [DEBUG] Provider `faker.providers.profile` does not feature localization. Specified locale `zh_CN` is not utilized for this provider. (factory.py:113)
2021-07-19 00:40:27 [DEBUG] Provider `faker.providers.python` does not feature localization. Specified locale `zh_CN` is not utilized for this provider. (factory.py:113)
2021-07-19 00:40:27 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.ssn`. (factory.py:94)
2021-07-19 00:40:27 [DEBUG] Provider `faker.providers.ssn` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:27 [DEBUG] Provider `faker.providers.user_agent` does not feature localization. Specified locale `zh_CN` is not utilized for this provider. (factory.py:113)
2021-07-19 00:40:27 [INFO] sending method:POST to url:https://qyapi.weixin.qq.com/cgi-bin/user/create?access_token=5Ny9MzxbrGVFqUiDStaOp3YGRS3F_uHqxa8ZvoK0Riq-S1KsDynpfOBBQA2TxDztSeA2sHfCmr9zfeTTZefNis9IPSpQ07cDc74iu1bq0yd1aeLsGTWgd_n146sGroFLIBKMVuYLA5cckgx0UVJxenjBsrTt2Nlz7t0XRPWgGal_N_cnDZrNTuTkYU1MvbfKF7xoGq4Sq7dKomLIJPOT3Q (base_api.py:23)
2021-07-19 00:40:27 [DEBUG] Starting new HTTPS connection (1): qyapi.weixin.qq.com:443 (connectionpool.py:971)
2021-07-19 00:40:28 [DEBUG] https://qyapi.weixin.qq.com:443 "POST /cgi-bin/user/create?access_token=5Ny9MzxbrGVFqUiDStaOp3YGRS3F_uHqxa8ZvoK0Riq-S1KsDynpfOBBQA2TxDztSeA2sHfCmr9zfeTTZefNis9IPSpQ07cDc74iu1bq0yd1aeLsGTWgd_n146sGroFLIBKMVuYLA5cckgx0UVJxenjBsrTt2Nlz7t0XRPWgGal_N_cnDZrNTuTkYU1MvbfKF7xoGq4Sq7dKomLIJPOT3Q HTTP/1.1" 200 32 (connectionpool.py:452)
2021-07-19 00:40:28 [DEBUG] add user result: {'errcode': 0, 'errmsg': 'created'} (user.py:19)
2021-07-19 00:40:28 [INFO] 1626626427current_thread (test_user.py:25)
2021-07-19 00:40:28 [INFO] sending method:POST to url:https://qyapi.weixin.qq.com/cgi-bin/user/update?access_token=5Ny9MzxbrGVFqUiDStaOp3YGRS3F_uHqxa8ZvoK0Riq-S1KsDynpfOBBQA2TxDztSeA2sHfCmr9zfeTTZefNis9IPSpQ07cDc74iu1bq0yd1aeLsGTWgd_n146sGroFLIBKMVuYLA5cckgx0UVJxenjBsrTt2Nlz7t0XRPWgGal_N_cnDZrNTuTkYU1MvbfKF7xoGq4Sq7dKomLIJPOT3Q (base_api.py:23)
2021-07-19 00:40:28 [DEBUG] Starting new HTTPS connection (1): qyapi.weixin.qq.com:443 (connectionpool.py:971)
2021-07-19 00:40:28 [DEBUG] https://qyapi.weixin.qq.com:443 "POST /cgi-bin/user/update?access_token=5Ny9MzxbrGVFqUiDStaOp3YGRS3F_uHqxa8ZvoK0Riq-S1KsDynpfOBBQA2TxDztSeA2sHfCmr9zfeTTZefNis9IPSpQ07cDc74iu1bq0yd1aeLsGTWgd_n146sGroFLIBKMVuYLA5cckgx0UVJxenjBsrTt2Nlz7t0XRPWgGal_N_cnDZrNTuTkYU1MvbfKF7xoGq4Sq7dKomLIJPOT3Q HTTP/1.1" 200 32 (connectionpool.py:452)
2021-07-19 00:40:28 [DEBUG] update user result: {'errcode': 0, 'errmsg': 'updated'} (user.py:56)
2021-07-19 00:40:28 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.address`. (factory.py:94)
2021-07-19 00:40:28 [DEBUG] Provider `faker.providers.address` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:28 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.automotive`. (factory.py:94)
2021-07-19 00:40:28 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.automotive`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:28 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.bank`. (factory.py:94)
2021-07-19 00:40:28 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider. (factory.py:101)
2021-07-19 00:40:28 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.barcode`. (factory.py:94)
2021-07-19 00:40:28 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.barcode`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:28 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.color`. (factory.py:94)
2021-07-19 00:40:28 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.color`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:28 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.company`. (factory.py:94)
2021-07-19 00:40:28 [DEBUG] Provider `faker.providers.company` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:28 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.credit_card`. (factory.py:94)
2021-07-19 00:40:28 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.credit_card`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:28 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.currency`. (factory.py:94)
2021-07-19 00:40:28 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.currency`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:28 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.date_time`. (factory.py:94)
2021-07-19 00:40:28 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.date_time`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:28 [DEBUG] Provider `faker.providers.file` does not feature localization. Specified locale `zh_CN` is not utilized for this provider. (factory.py:113)
2021-07-19 00:40:28 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.geo`. (factory.py:94)
2021-07-19 00:40:28 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.geo`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:28 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.internet`. (factory.py:94)
2021-07-19 00:40:28 [DEBUG] Provider `faker.providers.internet` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:28 [DEBUG] Provider `faker.providers.isbn` does not feature localization. Specified locale `zh_CN` is not utilized for this provider. (factory.py:113)
2021-07-19 00:40:28 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.job`. (factory.py:94)
2021-07-19 00:40:28 [DEBUG] Provider `faker.providers.job` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:28 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.lorem`. (factory.py:94)
2021-07-19 00:40:28 [DEBUG] Provider `faker.providers.lorem` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:28 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.misc`. (factory.py:94)
2021-07-19 00:40:28 [DEBUG] Specified locale `zh_CN` is not available for provider `faker.providers.misc`. Locale reset to `en_US` for this provider. (factory.py:101)
2021-07-19 00:40:28 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.person`. (factory.py:94)
2021-07-19 00:40:28 [DEBUG] Provider `faker.providers.person` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:28 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.phone_number`. (factory.py:94)
2021-07-19 00:40:28 [DEBUG] Provider `faker.providers.phone_number` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:28 [DEBUG] Provider `faker.providers.profile` does not feature localization. Specified locale `zh_CN` is not utilized for this provider. (factory.py:113)
2021-07-19 00:40:28 [DEBUG] Provider `faker.providers.python` does not feature localization. Specified locale `zh_CN` is not utilized for this provider. (factory.py:113)
2021-07-19 00:40:28 [DEBUG] Looking for locale `zh_CN` in provider `faker.providers.ssn`. (factory.py:94)
2021-07-19 00:40:28 [DEBUG] Provider `faker.providers.ssn` has been localized to `zh_CN`. (factory.py:106)
2021-07-19 00:40:28 [DEBUG] Provider `faker.providers.user_agent` does not feature localization. Specified locale `zh_CN` is not utilized for this provider. (factory.py:113)
2021-07-19 00:40:28 [INFO] sending method:POST to url:https://qyapi.weixin.qq.com/cgi-bin/user/create?access_token=5Ny9MzxbrGVFqUiDStaOp3YGRS3F_uHqxa8ZvoK0Riq-S1KsDynpfOBBQA2TxDztSeA2sHfCmr9zfeTTZefNis9IPSpQ07cDc74iu1bq0yd1aeLsGTWgd_n146sGroFLIBKMVuYLA5cckgx0UVJxenjBsrTt2Nlz7t0XRPWgGal_N_cnDZrNTuTkYU1MvbfKF7xoGq4Sq7dKomLIJPOT3Q (base_api.py:23)
2021-07-19 00:40:28 [DEBUG] Starting new HTTPS connection (1): qyapi.weixin.qq.com:443 (connectionpool.py:971)
2021-07-19 00:40:29 [DEBUG] https://qyapi.weixin.qq.com:443 "POST /cgi-bin/user/create?access_token=5Ny9MzxbrGVFqUiDStaOp3YGRS3F_uHqxa8ZvoK0Riq-S1KsDynpfOBBQA2TxDztSeA2sHfCmr9zfeTTZefNis9IPSpQ07cDc74iu1bq0yd1aeLsGTWgd_n146sGroFLIBKMVuYLA5cckgx0UVJxenjBsrTt2Nlz7t0XRPWgGal_N_cnDZrNTuTkYU1MvbfKF7xoGq4Sq7dKomLIJPOT3Q HTTP/1.1" 200 32 (connectionpool.py:452)
2021-07-19 00:40:29 [DEBUG] add user result: {'errcode': 0, 'errmsg': 'created'} (user.py:19)
2021-07-19 00:40:29 [INFO] sending method:GET to url:https://qyapi.weixin.qq.com/cgi-bin/user/delete?access_token=5Ny9MzxbrGVFqUiDStaOp3YGRS3F_uHqxa8ZvoK0Riq-S1KsDynpfOBBQA2TxDztSeA2sHfCmr9zfeTTZefNis9IPSpQ07cDc74iu1bq0yd1aeLsGTWgd_n146sGroFLIBKMVuYLA5cckgx0UVJxenjBsrTt2Nlz7t0XRPWgGal_N_cnDZrNTuTkYU1MvbfKF7xoGq4Sq7dKomLIJPOT3Q&userid=1626626428current_thread (base_api.py:23)
2021-07-19 00:40:29 [DEBUG] Starting new HTTPS connection (1): qyapi.weixin.qq.com:443 (connectionpool.py:971)
2021-07-19 00:40:29 [DEBUG] https://qyapi.weixin.qq.com:443 "GET /cgi-bin/user/delete?access_token=5Ny9MzxbrGVFqUiDStaOp3YGRS3F_uHqxa8ZvoK0Riq-S1KsDynpfOBBQA2TxDztSeA2sHfCmr9zfeTTZefNis9IPSpQ07cDc74iu1bq0yd1aeLsGTWgd_n146sGroFLIBKMVuYLA5cckgx0UVJxenjBsrTt2Nlz7t0XRPWgGal_N_cnDZrNTuTkYU1MvbfKF7xoGq4Sq7dKomLIJPOT3Q&userid=1626626428current_thread HTTP/1.1" 200 32 (connectionpool.py:452)
2021-07-19 00:40:29 [DEBUG] delete user result: {'errcode': 0, 'errmsg': 'deleted'} (user.py:61)
2021-07-19 00:40:29 [INFO] sending method:GET to url:https://qyapi.weixin.qq.com/cgi-bin/user/get?access_token=5Ny9MzxbrGVFqUiDStaOp3YGRS3F_uHqxa8ZvoK0Riq-S1KsDynpfOBBQA2TxDztSeA2sHfCmr9zfeTTZefNis9IPSpQ07cDc74iu1bq0yd1aeLsGTWgd_n146sGroFLIBKMVuYLA5cckgx0UVJxenjBsrTt2Nlz7t0XRPWgGal_N_cnDZrNTuTkYU1MvbfKF7xoGq4Sq7dKomLIJPOT3Q&userid=1626626428current_thread (base_api.py:23)
2021-07-19 00:40:29 [DEBUG] Starting new HTTPS connection (1): qyapi.weixin.qq.com:443 (connectionpool.py:971)
2021-07-19 00:40:29 [DEBUG] https://qyapi.weixin.qq.com:443 "GET /cgi-bin/user/get?access_token=5Ny9MzxbrGVFqUiDStaOp3YGRS3F_uHqxa8ZvoK0Riq-S1KsDynpfOBBQA2TxDztSeA2sHfCmr9zfeTTZefNis9IPSpQ07cDc74iu1bq0yd1aeLsGTWgd_n146sGroFLIBKMVuYLA5cckgx0UVJxenjBsrTt2Nlz7t0XRPWgGal_N_cnDZrNTuTkYU1MvbfKF7xoGq4Sq7dKomLIJPOT3Q&userid=1626626428current_thread HTTP/1.1" 200 244 (connectionpool.py:452)
2021-07-19 00:40:29 [DEBUG] get user result: {'errcode': 60111, 'errmsg': 'userid not found, hint: [1626626429_148_c8d0b3c535a26551abe277fedd020078], from ip: 101.88.10.151, more info at https://open.work.weixin.qq.com/devtool/query?e=60111', 'department': [], 'order': [], 'is_leader_in_dept': []} (user.py:24)
